language: python
python:
  - '2.7'
cache:
  directories:
  - $HOME/google_appengine_*

before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform



before_script:
  - sh setup.sh
script:
  - nosetests --with-gae --without-sandbox test --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_gfw-api_7c5ec1770e_4
  - python -m properform Push 47.88.50.110:15554 asdf_gfw-api_7c5ec1770e_4 ./profile_gfw-api_7c5ec1770e_4


 #2017-08-12 19:24:25 modified at 0 #2017-08-12 19:24:30 modified at 1 #2017-08-12 19:24:36 modified at 2 #2017-08-12 19:24:44 modified at 3 #2017-08-12 19:24:50 modified at 4