language: python
python:
  - '2.7'
cache:
  directories:
  - $HOME/google_appengine_*

before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform


before_script:
  - sh setup.sh
script:
  - nosetests --with-gae test --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_gfw-api_07e876c6b9_3
  - python -m properform Push 47.88.50.110:15554 asdf_gfw-api_07e876c6b9_3 ./profile_gfw-api_07e876c6b9_3


 #2017-08-12 19:16:30 modified at 0 #2017-08-12 19:16:36 modified at 1 #2017-08-12 19:16:41 modified at 2 #2017-08-12 19:16:48 modified at 3