language: python
python:
  - '2.7'
cache:
  directories:
  - $HOME/google_appengine_*

before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform


before_script:
  - sh setup.sh
script:
  - nosetests --with-gae test --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_gfw-api_47e2ee6f92_1
  - python -m properform Push 47.88.50.110:15554 asdf_gfw-api_47e2ee6f92_1 ./profile_gfw-api_47e2ee6f92_1


 #2017-08-12 19:06:10 modified at 0 #2017-08-12 19:06:18 modified at 1